### ISSUE TITLE
Feature request: Implement IRP notation

### ISSUE THREAD

**Issue by probonopd** [cyborg5/IRLib#1]
Wouldn't it be cool if we could send the Arduino a command like:

SEND NEC1 0 191 1

and it would correctly send the code (but not just for a handful but for ALL protocols)?

John S. Fine, who is the original IRP inventor, writes on http://www.remotecentral.com/cgi-bin/forums/viewpost.cgi?811010

"The easiest way to make a generator for many different protocols (such as a universal remote) would be to make a program that understands IRP notation and uses it as the guide to generating the signals. My MakeHex program (source code available at [Link: john.fine.home.comcast.net] ) generates Pronto Hex from an older form of IRP notation. It is a good C++ example of how to translate from an IRP notation to the actual signal."

**Comment by probonopd** [comment]
I tried to convert MakeHex to Arduino and it appears to start working, but it still has some issues (among which a memory leak) that I was not able to fix so far. Maybe you'd like to have a look at it. https://github.com/probonopd/MakeHex/tree/arduino/encodeir

**Comment by bengtmartensson** [comment]
I hate to stop enthusiasts, but I doubt this is a good idea. The IRP version implemented in Makehex is obsolete, current is the version 2, which is implemented in https://github.com/bengtmartensson/harctoolboxbundle/tree/master/IrpMaster. (took a few months and several thousands of lines in Java, still not implementing the (practically completely useless) hierarchical repetitions.) There is a vast difference between version 1 and 2. And John Fine's code is of quite low quality, writing outside of array limits, incorrectly rounding, etc (note that Makehex NEC1 signal contains both 0015 and 0016 :-))

Instead, I suggest having a program like IrpMaster _generate Arduino C++-code_ (or a complete sketch) that can be incorporated in a sender that is capable of rendering and sending these signals?

**Comment by cyborg5** [comment]
I tend to agree that converting IRP into something that Arduino could use would best be left to a standalone program that would extract timing values that could then be implemented in C++ code.
