### ISSUE TITLE
Compile Errors with Due

### ISSUE THREAD

**Issue by romwhite** [cyborg5/IRLib#19]
I am using the current 1.51 version of the library and continue to get the same compile errors seen by others. I've looked into other IR libraries that claim to be for the Due but they don't have the decoding for the number of protocols this one does or flat out aren't as user friendly. Unfortunately, this things I want to do require the use of the Due instead of the Uno since I need USB HID support. Flashing the Uno firmware mentioned on some sites seems pretty advanced and involved. 

I am using Arduino IDE 1.6.7 with IRlib 1.51. Any ideas on how to work around this? I'm not an advanced programmer.

**Comment by cyborg5** [comment]
We don't officially support Due. Currently we only support eight bit AVR style processors. If you need USB HID support I suggest a Leonardo or Micro. Are you trying to send or receive? If you are sending only, you could try the bit-bang option which is hardware independent for the most part. If you are receiving, try the IRrecvLoop receiver which is also hardware independent. There are some options that you will have to disable the IRrecv code and perhaps the attach interrupts as well. Look in IRLib.h for the defines you can comment out to disable those features.

**Comment by TrippyLighting** [comment]
I just wanted to mention that while 32 bit micro controllers are not officially supported the Teensy processors are supported as another user and I aded the necessary code to the library for the Teensy 3.x and the Teensy LC. While the Freescale Arm Cortex chips the are used on the Teensy boards are different from the one on the Due, they are also 32 bit microprocessors.

The link to the modified library, which also includes an additional Panasonic IR protocol is this:
https://forum.pjrc.com/threads/26070-Updated-modified-Version-from-cyborgs-irlib?p=91859&viewfull=1#post91859
