### ISSUE TITLE
Old IRLib used to work

### ISSUE THREAD

**Issue by inkocus** [cyborg5/IRLib#23]
This code used to work with the old library:
My_Sender.sendNEC(0x0CC7C1F3, 32); // Canon HF10 Photo button

But when I changed it to:

My_Sender.send(NEC,0x0CC7C1F3, 32); // Canon HF10 Photo button

it compiles but doesn't send the IR code to my camera.

Any ideas?

**Comment by cyborg5** [comment]
IRLib is no longer supported. You should try IRLib2 which is available at https://github.com/cyborg5/IRLib2

I cannot understand why that particular piece of code would not work. There has been no significant change in the NEC protocol code.
