### ISSUE TITLE
README.md

### ISSUE THREAD

**Issue by ivanpanasiuk** [cyborg5/IRLib#27]
There is a small typo - the link to the IRLib2 is not working in the README.md

**Comment by ElectricRCAircraftGuy** [comment]
Looks like his readme has a bunch of minor formatting issues making it not display correctly as Markdown. Meanwhile, here's the correct link: https://github.com/cyborg5/IRLib2.

**Comment by ElectricRCAircraftGuy** [comment]
@cyborg5 , you accidentally called it "IRLib1 on GitHub" instead of "IRLib2 on GitHub" in your readme just now.

**Comment by cyborg5** [comment]
Thanks.
